[default.extend-words]
tema = "tema"
Mihomo = "Mihomo"
mihomo = "mihomo"
Mihoro = "Mihoro"
cliamp = "cliamp"
SHIBUMI = "SHIBUMI"
Okomart = "Okomart"
Omagen = "Omagen"
Omaland = "Omaland"
Omalibre = "Omalibre"
Omamail = "Omamail"
omaplug = "omaplug"
Quattrolitaire = "Quattrolitaire"
Voxtype = "Voxtype"
hyprmoncfg = "hyprmoncfg"
OmaConnect = "OmaConnect"
